[work.volume]
deltaX = 11 # downstream
deltaY = 3  # up-down
deltaZ = 24 # left-right

[stock.volume]
deltaX = 8 # downstream
deltaY = 2  # up-down
# deltaZ = 11.91 # left-right


[stock.offset]
# The position of the stock in absolute machine coords location of the front bottom left of the stock
absoluteX = 0.25
absoluteY = 0.0
absoluteZ = 6.25 # negative taken as offset from left, positive taken as offset from right


[cut]
kerf = 0.06
feedrate = 300
rapid = 1000
leading_edge_offsetY = 0.5
section = 2
