[work.volume]
deltaX = 20 # downstream
deltaY = 5  # up-down
deltaZ = 20 # left-right

[stock.volume]
deltaX = 8 # downstream
deltaY = 2  # up-down
# deltaZ = 11.91 # left-right


[stock.offset]
# The position of the stock in absolute machine coords location of the front bottom left of the stock
absoluteX = 3
absoluteY = 0
absoluteZ = -3

side = +1 # +1 for left positive Z side, -1 for negative Z side

[cut]
kerf = 0.1
feedrate = 300
rapid = 1000

